// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBpitZbTXHhOOve3RkHApVtUoYRId0s4',
    appId: '1:828488657826:web:c886f968638f29742b20fb',
    messagingSenderId: '828488657826',
    projectId: 'tipon-timekeeper',
    authDomain: 'tipon-timekeeper.firebaseapp.com',
    storageBucket: 'tipon-timekeeper.firebasestorage.app',
    measurementId: 'G-NKD8H31WP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgx0utbLZB717izfkow1mx8T3PNxUQwE',
    appId: '1:828488657826:android:8369b824547a17412b20fb',
    messagingSenderId: '828488657826',
    projectId: 'tipon-timekeeper',
    storageBucket: 'tipon-timekeeper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXp6ozXKKtWT9Ynf1rVIZz86mQW-0sTA',
    appId: '1:828488657826:ios:dd6e4249e59ed1822b20fb',
    messagingSenderId: '828488657826',
    projectId: 'tipon-timekeeper',
    storageBucket: 'tipon-timekeeper.firebasestorage.app',
    iosBundleId: 'com.example.tiponTimekeepingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXp6ozXKKtWT9Ynf1rVIZz86mQW-0sTA',
    appId: '1:828488657826:ios:dd6e4249e59ed1822b20fb',
    messagingSenderId: '828488657826',
    projectId: 'tipon-timekeeper',
    storageBucket: 'tipon-timekeeper.firebasestorage.app',
    iosBundleId: 'com.example.tiponTimekeepingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFBpitZbTXHhOOve3RkHApVtUoYRId0s4',
    appId: '1:828488657826:web:d542f38924dde54a2b20fb',
    messagingSenderId: '828488657826',
    projectId: 'tipon-timekeeper',
    authDomain: 'tipon-timekeeper.firebaseapp.com',
    storageBucket: 'tipon-timekeeper.firebasestorage.app',
    measurementId: 'G-7V5H9TRQMC',
  );
}
